import re
print(re.findall(r"\d+", "a1 bb22 ccc333"))
m = re.search(r"(\w+)@(\w+)\.com", "mail kami@example.com end")
print(m.group(0), m.group(1), m.group(2), m.start(), m.end())
print(re.match(r"[Hh]ello", "hello").group())
print(re.match(r"xyz", "hello") is None)
print(re.fullmatch(r"\d{3}-\d{4}", "123-4567") is not None)
print(re.sub(r"\s+", "_", "a   b  c"))
print(re.sub(r"(\w+)=(\d+)", r"\2:\1", "x=1 y=22"))
print(re.split(r"[,;]\s*", "a, b;c ,d"))
print(re.findall(r"[aeiou]", "education"))
print(re.search(r"colou?r", "the color").group())
print(re.search(r"\bcat\b", "a cat") is not None, re.search(r"\bcat\b", "scatter") is not None)
print(re.findall(r"ab|cd", "ab cd ab"))
print(re.sub(r"a+", "A", "aaa b a c"))
